name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 或 master，如果你主分支叫 master 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

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
